---
name: CI
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:

permissions:
  contents: write

jobs:
  ci:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v2
    - name: Print Swift Version
      run: swift --version
    - name: Test
      run: swift test
    - name: Build
      run: swift build -v
    - name: Upload Executable to GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git show "${{ github.ref_name }}" --no-patch
        mv ./.build/release/boot boot-${{ github.ref_name }}-${{ matrix.os }}
        gh release upload ${{ github.ref_name }} boot-${{ github.ref_name }}-${{ matrix.os }}
