---
name: CI
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:

jobs:
  ci:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: swift test
    - name: Build
      run: swift build -v
